version: 2
jobs:
  gcc5:
    docker:
      - image: docker.retrieva.jp/pficommon_ci:gcc5.2007
        auth:
          username: $DOCKER_REPO_USER
          password: $DOCKER_REPO_PASSWORD
    steps:
      - checkout
      - run:
          name: configure
          command: CPPFLAGS="-I/usr/include/postgresql" ./waf configure
      - run:
          name: build
          command: ./waf build -j4
      - run:
          name: test
          command: LD_LIBRARY_PATH="/usr/local/lib" ./waf --check -j4
      - run:
          name: install
          command: ./waf install
  gcc6:
    docker:
      - image: docker.retrieva.jp/pficommon_ci:gcc6.2007
        auth:
          username: $DOCKER_REPO_USER
          password: $DOCKER_REPO_PASSWORD
    steps:
      - checkout
      - run:
          name: configure
          command: CPPFLAGS="-I/usr/include/postgresql" ./waf configure
      - run:
          name: build
          command: ./waf build -j4
      - run:
          name: test
          command: LD_LIBRARY_PATH="/usr/local/lib" ./waf --check -j4
      - run:
          name: install
          command: ./waf install
  gcc7:
    docker:
      - image: docker.retrieva.jp/pficommon_ci:gcc7.2007
        auth:
          username: $DOCKER_REPO_USER
          password: $DOCKER_REPO_PASSWORD
    steps:
      - checkout
      - run:
          name: configure
          command: CPPFLAGS="-I/usr/include/postgresql" ./waf configure
      - run:
          name: build
          command: ./waf build -j4
      - run:
          name: test
          command: LD_LIBRARY_PATH="/usr/local/lib" ./waf --check -j4
      - run:
          name: install
          command: ./waf install
  gcc8:
    docker:
      - image: docker.retrieva.jp/pficommon_ci:gcc8.2007
        auth:
          username: $DOCKER_REPO_USER
          password: $DOCKER_REPO_PASSWORD
    steps:
      - checkout
      - run:
          name: configure
          command: CPPFLAGS="-I/usr/include/postgresql" ./waf configure
      - run:
          name: build
          command: ./waf build -j4
      - run:
          name: test
          command: LD_LIBRARY_PATH="/usr/local/lib" ./waf --check -j4
      - run:
          name: install
          command: ./waf install
  gcc9:
    docker:
      - image: docker.retrieva.jp/pficommon_ci:gcc9.2007
        auth:
          username: $DOCKER_REPO_USER
          password: $DOCKER_REPO_PASSWORD
    steps:
      - checkout
      - run:
          name: configure
          command: CPPFLAGS="-I/usr/include/postgresql" ./waf configure
      - run:
          name: build
          command: ./waf build -j4
      - run:
          name: test
          command: LD_LIBRARY_PATH="/usr/local/lib" ./waf --check -j4
      - run:
          name: install
          command: ./waf install
workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc5
      - gcc6
      - gcc7
      - gcc8
      - gcc9
